#!/usr/bin/env python3
"""Fetch Nyaa titles using search with different anime terms."""

import json
import urllib.request
import sys
import random
from collections import OrderedDict

# Common anime search terms
search_terms = [
    "naruto",
    "one piece",
    "bleach",
    "fairy tail",
    "attack on titan",
    "demon slayer",
    "my hero academia",
    "dragon ball",
    "pokemon",
    "pokémon",
    "sailor moon",
    "cardcaptor",
    "digimon",
    "yugioh",
    "sword art online",
    "re:zero",
    "no game no life",
    "overlord",
    "sao",
    "fate",
    "steins gate",
    "code geass",
    "death note",
    "fullmetal alchemist",
    "cowboy bebop",
    "trigun",
    "outlaw star",
    "neon genesis",
    "evangelion",
    "gundam",
    " Gundam",
    "gintama",
    "jojo",
    "hunter x hunter",
    "HxH",
    "one punch man",
    "mob psycho",
    "haikyuu",
    "kuroko",
    "yuri on ice",
    "blue lock",
    "haikyu",
    "rezero",
    "spice and wolf",
    "toradora",
    "clannad",
    "angel beats",
    "your name",
    "weathering with you",
    "spirited away",
    "ghibli",
    "violet evergarden",
    "cyberpunk",
    "cowboy",
    "slayers",
    "log horizon",
    "kono subarashii",
    "konosuba",
    "shield hero",
    "mushoku tensei",
    "isekai",
    "isekai anime",
    "shingeki",
    "snk",
    "aot",
    "blue exorcist",
    "assassination classroom",
    "erased",
    "your lie",
    "a silent voice",
    "kakegurui",
    "dr stone",
    "fire force",
    " Jujutsu",
    "jujutsu kaisen",
    "chainsaw man",
    "cs m",
    "spy x family",
    "squid game",
    "cyberpunk edgerunners",
    "vivy",
    "frieren",
    "sousou no frieren",
    "frieren",
    "sousou",
    "dandadan",
    "RANMA",
    "rumble",
    "ranma",
    "slam dunk",
    "slamdunk",
    "urusei yatsura",
    "lupin",
    "lupin the third",
    "celestial",
    "witch craft",
    "k-on",
    "hibike euphonium",
    "bang dream",
    "love live",
    "idolm@ster",
    "kanon",
    "air",
    "clannad",
    "fruit basket",
    "furuba",
    "ouran",
    "host club",
    "kamigami",
    "shaman king",
    "inuyasha",
    "yu yu hakusho",
    "rurouni kenshin",
    "samurai deeper kyo",
    "kenichi",
    "magi",
    "aladdin",
    "labyrinth",
    "nanatsu no taizai",
    "seven deadly sins",
    " SDS",
    "black clover",
    "boruto",
    "boruto anime",
    "boruto naruto",
    "meiji tokyo",
    "kuroshitsuji",
    "black butler",
    "servant",
    "beast tamer",
    "bofuri",
    "doesn't know",
    "mushoku",
    "tensei",
    "reincarnated",
    "sage",
    "jobless",
    "reincarnation",
    "slime",
    "tensei shitara",
    "that time i got reincarnated",
    "ascension",
    "so i'm a spider",
    "spider",
    "arachnoid",
    "saiyuki",
    "inuyasha",
    "yakou",
    "genshin",
    "genshin impact",
    "zenless",
    "zone",
    "zone 0",
    "zatch bell",
    "konjiki",
    "conqueror",
    "baki",
    "yujiro",
    "kengan ashura",
    "fighter",
    "kengan",
    "ashura",
    " Gracian",
    "grand blue",
    "blue",
    "diving",
    "blue lock",
    "bluelock",
    "blue",
    "locker",
    "uncle",
    "i have",
    "uncle from another world",
    "isekai",
    "isekai anime",
    "isekai slime",
    "isekai saibou",
    "isekai smartphone",
    "isekai mahjong",
    "isekai cooking",
    "isekai tavern",
    "isekai academy",
    "isekai princess",
    "isekai knight",
    "isekai vampire",
    "isekai werewolf",
    "isekai dragon",
    "isekai elf",
    "isekai dwarf",
    "isekai goblin",
    "isekai orc",
    "isekai demon",
    "isekai angel",
    "isekai ghost",
]

seen = OrderedDict()

# Try search with different terms
for term in search_terms[:50]:
    url = f"https://nyaaapi.onrender.com/nyaa?term={term}&c=1_2&limit=50"
    try:
        data = json.loads(urllib.request.urlopen(url, timeout=5).read())
        for item in data.get("data", []):
            t = item.get("title", "").strip()
            if t and t not in seen:
                seen[t] = True
    except Exception as e:
        print(f"Error: {term}: {e}", file=sys.stderr)

print(f"Total unique from search: {len(seen)}", file=sys.stderr)

# Also get recent
url = "https://nyaaapi.onrender.com/nyaa?c=1_2&limit=200"
data = json.loads(urllib.request.urlopen(url).read())
for item in data.get("data", []):
    t = item.get("title", "").strip()
    if t and t not in seen:
        seen[t] = True

print(f"Total with recent: {len(seen)}", file=sys.stderr)

titles = list(seen.keys())
with open("data/training/nyaa_titles_5000_raw.txt", "w") as f:
    for i, t in enumerate(titles, 1):
        f.write(f"({i}) {t}\n")

print(f"Saved {len(titles)} titles", file=sys.stderr)
